# Generated by Django 3.0.7 on 2020-06-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='status',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='task_duration',
        ),
        migrations.AddField(
            model_name='upload',
            name='user_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
