# Generated by Django 3.0.7 on 2020-06-18 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20200609_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='user_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
