# Generated by Django 3.0.7 on 2020-06-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20200618_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(null=True, upload_to='media/screens_py'),
        ),
    ]
