# Generated by Django 3.0.6 on 2020-05-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten',
            name='short_url',
            field=models.SlugField(),
        ),
    ]
